#ifndef LISTITEM_GLOBAL_H
#define LISTITEM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LISTITEM_LIBRARY)
#  define LISTITEMSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LISTITEMSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LISTITEM_GLOBAL_H
