#ifndef ROADOVERWAVECODER_GLOBAL_H
#define ROADOVERWAVECODER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ROADOVERWAVECODER_LIBRARY)
#  define ROADOVERWAVECODERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ROADOVERWAVECODERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ROADOVERWAVECODER_GLOBAL_H
