#ifndef AUDIOFORMATREADER_GLOBAL_H
#define AUDIOFORMATREADER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(AUDIOFORMATREADER_LIBRARY)
#  define AUDIOFORMATREADERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define AUDIOFORMATREADERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // AUDIOFORMATREADER_GLOBAL_H
