#ifndef ENCODINGOPTIONSWIDGETFACTORY_GLOBAL_H
#define ENCODINGOPTIONSWIDGETFACTORY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ENCODINGOPTIONSWIDGETFACTORY_LIBRARY)
#  define ENCODINGOPTIONSWIDGETFACTORYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ENCODINGOPTIONSWIDGETFACTORYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ENCODINGOPTIONSWIDGETFACTORY_GLOBAL_H
