#ifndef LISTITEMSMODEL_GLOBAL_H
#define LISTITEMSMODEL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LISTITEMSMODEL_LIBRARY)
#  define LISTITEMSMODELSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LISTITEMSMODELSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LISTITEMSMODEL_GLOBAL_H
